// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartBuilding_gRPC.Models;

#nullable disable

namespace SmartBuilding_gRPC.Migrations
{
    [DbContext(typeof(SmartBuildingDbContext))]
    partial class SmartBuildingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartBuilding_gRPC.Models.RoomValues", b =>
                {
                    b.Property<string>("ValueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("CO2")
                        .HasColumnType("real");

                    b.Property<float>("Humidity")
                        .HasColumnType("real");

                    b.Property<float>("Light")
                        .HasColumnType("real");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("ValueId");

                    b.ToTable("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
